extends RefCounted
class_name UIStyle
## Shared palette, theme access and drawing helpers for every RADIUS Control.
## The theme itself is generated by scripts/ui/theme_builder.gd into scenes/ui/theme.tres; this class is the
## code-side companion for widgets that paint themselves with _draw() and for modules that need a colour
## without a Control in hand.
##
##   UIStyle.theme()                     -> Theme (loads the .tres once, rebuilds in memory if missing)
##   UIStyle.font(control, "caps")       -> Font  (falls back to the control's default font)
##   UIStyle.size(control, "small")      -> int
##   UIStyle.color(control, "amber")     -> Color
##   UIStyle.caps(text)                  -> uppercased register text
##   UIStyle.dot_join(["SEARCH", "CRATE"]) -> "SEARCH · CRATE"
##   UIStyle.money(1800)                 -> "1 800 ₽"
##   UIStyle.hairline(ci, from, to, col, alpha)
##   UIStyle.dotted(ci, from, to, col, step)
##   UIStyle.brushed_disc(ci, centre, r0, r1, base, seed)   brushed-steel ring, no gradients, all hairlines

const THEME_PATH := "res://scenes/ui/theme.tres"

const INK := Color("1a1917")
const PAPER := Color("d9d3c4")
const PAPER_DIM := Color(0.851, 0.827, 0.769, 0.72)
const PAPER_FAINT := Color(0.851, 0.827, 0.769, 0.42)
const PAPER_HAIR := Color(0.851, 0.827, 0.769, 0.22)
const AMBER := Color("e0a458")
const AMBER_INK := Color("a8672a")
const RED := Color("a23b2a")
const RED_INK := Color("8b2d20")
const RUST := Color("7a4a2a")
const STEEL := Color("8a9098")
const OLIVE := Color("4b5540")
const BIRCH := Color("c9c6bd")
const CONCRETE := Color("6e6b66")
const PINK := Color("ff6fa8")
const CYAN := Color("7fe8ff")
const SLATE := Color("14130f")
const BLACK := Color("0a0a09")
const LUME := Color(0.72, 0.86, 0.66)

static var _theme: Theme = null

static func theme() -> Theme:
	if _theme != null:
		return _theme
	if ResourceLoader.exists(THEME_PATH):
		var t: Variant = load(THEME_PATH)
		if t is Theme:
			_theme = t
			return _theme
	var builder: Variant = load("res://scripts/ui/theme_builder.gd")
	if builder != null and builder.has_method("build"):
		_theme = builder.build()
	else:
		_theme = Theme.new()
	return _theme

static func font(c: Control, name: String) -> Font:
	if c != null and c.has_theme_font(name, "Radius"):
		return c.get_theme_font(name, "Radius")
	var t := theme()
	if t.has_font(name, "Radius"):
		return t.get_font(name, "Radius")
	if t.default_font != null:
		return t.default_font
	return ThemeDB.fallback_font

static func size(c: Control, name: String) -> int:
	if c != null and c.has_theme_font_size(name, "Radius"):
		return c.get_theme_font_size(name, "Radius")
	var t := theme()
	if t.has_font_size(name, "Radius"):
		return t.get_font_size(name, "Radius")
	return 13

static func color(c: Control, name: String) -> Color:
	if c != null and c.has_theme_color(name, "Radius"):
		return c.get_theme_color(name, "Radius")
	var t := theme()
	if t.has_color(name, "Radius"):
		return t.get_color(name, "Radius")
	return PAPER

## Register text helpers ------------------------------------------------------------------------------
static func caps(s: String) -> String:
	return s.to_upper()

static func dot_join(parts: Array) -> String:
	var keep: Array[String] = []
	for p in parts:
		var s := str(p).strip_edges()
		if s != "":
			keep.append(s)
	return " · ".join(keep)

static func money(v: int) -> String:
	var s := str(absi(v))
	var out := ""
	var n := s.length()
	for i in n:
		if i > 0 and (n - i) % 3 == 0:
			out += " "
		out += s[i]
	return ("-" if v < 0 else "") + out + " ₽"

static func metres(d: float) -> String:
	if d >= 1000.0:
		return "%.1f KM" % (d / 1000.0)
	return "%d M" % int(round(d))

## Drawing helpers ------------------------------------------------------------------------------------
static func hairline(ci: CanvasItem, from: Vector2, to: Vector2, col: Color, alpha: float = 1.0) -> void:
	ci.draw_line(from, to, Color(col.r, col.g, col.b, col.a * alpha), 1.0, false)

static func dotted(ci: CanvasItem, from: Vector2, to: Vector2, col: Color, step: float = 4.0) -> void:
	var d := to - from
	var n := int(d.length() / step)
	if n <= 0:
		return
	var u := d / float(n)
	for i in n:
		if i % 2 == 0:
			ci.draw_line(from + u * float(i), from + u * (float(i) + 0.55), col, 1.0, false)

## A brushed steel ring drawn as hundreds of jittered hairlines — procedural, no gradient fill.
static func brushed_disc(ci: CanvasItem, centre: Vector2, r0: float, r1: float, base: Color, seed_v: int = 7) -> void:
	var rng := RandomNumberGenerator.new()
	rng.seed = seed_v
	var steps := int(clampf((r1 - r0) * 6.0 + 160.0, 160.0, 520.0))
	for i in steps:
		var a := TAU * float(i) / float(steps)
		var v := rng.randf()
		# the light sits up and left: the top-left arc is bright, the lower right is shadow
		var lit: float = 0.55 + 0.45 * cos(a + 2.3)
		var k: float = 0.62 + lit * 0.7 + (v - 0.5) * 0.22
		var c := Color(base.r * k, base.g * k, base.b * k, base.a)
		var dir := Vector2(cos(a), sin(a))
		ci.draw_line(centre + dir * r0, centre + dir * r1, c, 1.6, false)

static func ring(ci: CanvasItem, centre: Vector2, r: float, col: Color, w: float = 1.0) -> void:
	ci.draw_arc(centre, r, 0.0, TAU, maxi(24, int(r * 1.2)), col, w, false)

## Greedy word wrap that returns fixed lines, so a typewriter reveal never reflows mid-word.
static func wrap_lines(f: Font, size_px: int, text: String, width: float) -> PackedStringArray:
	var out := PackedStringArray()
	for para in text.split("\n"):
		var line := ""
		for word in str(para).split(" "):
			var probe: String = word if line == "" else line + " " + word
			if f.get_string_size(probe, HORIZONTAL_ALIGNMENT_LEFT, -1, size_px).x <= width or line == "":
				line = probe
			else:
				out.append(line)
				line = word
		out.append(line)
	return out

## Draw text with a hard 1 px ink edge so it stays readable over grass, sky or snow without a drop shadow.
static func stencil(ci: CanvasItem, f: Font, at: Vector2, text: String, size_px: int, col: Color, edge: float = 0.75) -> void:
	var e := Color(0.03, 0.03, 0.025, col.a * edge)
	for o in [Vector2(-1, 0), Vector2(1, 0), Vector2(0, -1), Vector2(0, 1)]:
		ci.draw_string(f, at + o, text, HORIZONTAL_ALIGNMENT_LEFT, -1, size_px, e)
	ci.draw_string(f, at, text, HORIZONTAL_ALIGNMENT_LEFT, -1, size_px, col)
