extends Node
## Mixer and playback helpers. Sounds live in res://assets/audio/<name>[_N].ogg (generated by tools/gen_audio.py).
## play(name, pos) picks a random variant; loops return the player so callers can retune/stop it.
var _pool: Array[AudioStreamPlayer3D] = []
var _pool2d: Array[AudioStreamPlayer] = []
var _cache := {}
var missing := {}
const POOL := 48

func _ready() -> void:
	for i in POOL:
		var p := AudioStreamPlayer3D.new(); p.bus = "SFX"; p.max_distance = 250.0; p.unit_size = 2.5; p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE; add_child(p); _pool.append(p)
	for i in 12:
		var p := AudioStreamPlayer.new(); p.bus = "SFX"; add_child(p); _pool2d.append(p)

func _stream(name: String) -> Variant:
	# returns an AudioStream, an Array of variant streams, or null; callers pick a variant
	if _cache.has(name): return _cache[name]
	var dir := "res://assets/audio/"
	var candidates := []
	for suffix in ["", "_1", "_2", "_3", "_4"]:
		var path: String = dir + name + suffix + ".ogg"
		if ResourceLoader.exists(path): candidates.append(path)
	if candidates.is_empty():
		missing[name] = true; _cache[name] = null; return null
	var streams := []
	for c in candidates: streams.append(load(c))
	_cache[name] = streams
	return streams[randi() % streams.size()]

func play(name: String, pos = null, gain: float = 1.0, pitch: float = 1.0, bus: String = "SFX") -> Node:
	var st: Variant = _stream(name)
	if st == null: return null
	if st is Array: st = st[randi() % st.size()]
	if pos == null:
		for p in _pool2d:
			if not p.playing:
				p.stream = st; p.volume_db = linear_to_db(gain); p.pitch_scale = pitch * randf_range(0.96, 1.04); p.bus = bus; p.play(); return p
		return null
	for p in _pool:
		if not p.playing:
			p.global_position = pos; p.stream = st; p.volume_db = linear_to_db(gain); p.pitch_scale = pitch * randf_range(0.96, 1.04); p.bus = bus; p.play(); return p
	return null

func loop(name: String, pos = null, gain: float = 1.0, bus: String = "Ambience") -> Node:
	var st: Variant = _stream(name)
	if st == null: return null
	if st is Array: st = st[0]
	if pos == null:
		var p := AudioStreamPlayer.new(); p.stream = st; p.bus = bus; p.volume_db = linear_to_db(gain); add_child(p); p.play(); return p
	var p3 := AudioStreamPlayer3D.new(); p3.stream = st; p3.bus = bus; p3.volume_db = linear_to_db(gain); p3.max_distance = 120.0; add_child(p3); p3.global_position = pos; p3.play(); return p3

func has(name: String) -> bool: return _stream(name) != null
