extends Node
## Signal bus. Every cross-module event is a signal here so subsystems never reference each other directly.
signal game_started(new_game: bool)
signal player_damaged(amount: float, info: Dictionary)
signal player_died(info: Dictionary)
signal player_hit(info: Dictionary)
signal footstep(surface: String, sprint: bool, crouch: bool)
signal inventory_changed(id: String, delta: int)
signal earned(amount: int)
signal enemy_spawned(enemy: Node)
signal enemy_hit(enemy: Node, amount: float, info: Dictionary)
signal enemy_killed(enemy: Node, info: Dictionary)
signal director_state(state: String, prev: String)
signal director_notify(kind: String, data: Dictionary)
signal director_event(name: String)
signal new_day(day: int)
signal tide_warning(kind: String)
signal tide_now()
signal tide_rising()
signal tide(level: int)
signal enter_base()
signal exit_base()
signal mission_accepted(m: Dictionary)
signal mission_completed(m: Dictionary)
signal mission_failed(m: Dictionary)
signal artifact_picked(id: String)
signal anomaly_revealed(a: Node)
signal weapon_fired(w: Dictionary)
signal weapon_jammed(w: Dictionary)
signal sleep()
signal mode_changed(mode: String)
signal render_scale(scale: float)
signal world_ready()
signal weather_changed(weather: String, prev: String)
signal quality_changed(preset: String)
signal open_panel(name: String, data: Dictionary)
signal close_panel()
signal notice(text: String, kind: String)
